### PR TITLE
Acekard/Wood Menu Theme and improved settings menu.

### PR DESCRIPTION
**Pull request by RonnChyran**
#### What's new?
This pull request implements a fully featured DSiMenu++ theme based on the UI code of Wood 1.25. 

This theme supports user customizable sub themes in the  `_nds/dsimenuplusplus/akmenu/themes` directory. If no themes are available, or an invalid theme is selected for some reason, the default `zelda` theme will be loaded from nitrofs.
As part of this pull request, in order to allow user-customizable theme selection for akMenu, a rewrite of the `titleandsettings` UI was required. 

The changes made to titleandsettings were as follows.
* Use a singleton object `ms()` instead of global variables to access settings.
* Use a singleton object `sys()` instead of global variables to access system properties (such as `arm7SCFGlocked`
* Replace the state machine settings menu implementation with an abstracted GUI class `SettingsGUI`
* Options are now defined declaratively through the classes defined in `settingspage.h`.

Extensive documentation has been provided for the settings API used to define the settings menu.

#### Progress Tracking

**Feature Parity**
- [x] Port akMenu Drawing Primitives
- [x] Port akMenu Font Primitives
- [x] Port akMenu UI Windowing API
- [x] Port akMenu Auxillary Windows
- [x] Port akMenu Main Window (Game List)
- [x] Show .launchargs in Game List
- [x] Show TWL Icons in Game List
- [x] Show NES/GB ROMs in Game List
  - [x] Banners for .NES and .GB(C) ROMs
- [x] Show fixed banners in Game List
- [x] Make akMenu launch games with nds-bootstrap
- [x] Implement per game settings for bootstrap.
- [x] Make akMenu launch games with flashcarts
- [x] Make akMenu launch games with Unlaunch
- [x] Make akMenu allow for direct booting of homebrew
- [x] Implement akMenu Settings window for per-game settings
- [x] Make akMenu launch bootstrap games with per-game settings
- [x] Add auxillary launch options
  - [x] System settings
  - [x] DSi System Settings
  - [x] GBARunner2
  - [x] SLOT-1 Launch
  - [x] System Menu Launch (if on DSi)
- [x] Harmonize akMenu settings with DSiMenu++ Settings
  - [x] Remove dependency on Acekard settings 
  - [x] Read from DSiMenu++ Settings INI file.
  - [x] Add akMenu specific options to titleandsettings 
    - [x] Rewrite titleandsettings base
    - [x] Re-implement GUI settings
    - [x] Re-implement Games and Apps settings
    - [x] Re-implement sub theme select for DSiMenu/R4Menu
    - [x] Re-implement flashcard settings
   -  [x] Re-implement autoboot settings. 
    - [x] Implement akMenu settings
    - [x] Implement akMenu theme select
    - [x] Cleanup and documentation
- [x] Add akMenu entry to titleandsettings
- [x] Implement dynamic subtheme selection in titleandsettings
- [x] Cleanup akMenu API
  - [x] Remove GlobalSettings dependencies for UI drawing
  - [x] Strip out flashcart specific code

**User proofing**
- [x] Load zelda theme from NitroFS if selected theme is not available or is missing files.

*** 

#### Pull Request status
- [x]  This PR has been tested using latest devkitPro, devkitARM, and EasyGL2D.  

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by RonnChyran** [comment]
This PR is now OK to merge. It probably should be squash merged seeing as how 180-ish commits will probably clog up the commit history.

**Comment by RonnChyran** [comment]
## Remaining things left to do in the future
* The cheats window should be ported whenever the other themes get cheat support. Right now the story for handling cheats within DSiMenu++ is unclear
* Translations in akMenu are incomplete for languages besides English and Japanese.

**Comment by NightYoshi370** [comment]
I & @MarioGamer (TWLoader translater) can help out with French
@Samplasion & @moonlightcapital can help with Italian

**Comment by NightYoshi370** [comment]
Whoops, meant to ping this dude: https://github.com/mariogamer2. @mariogamer2

**Comment by RonnChyran** [comment]
Check `romsel_aktheme/nitrofiles/languages` for the language options. The ones that need translating are at the bottom of the file,  there's also `setting` in the `[rom info]` section as well.

**Pull request merged**
