### PR TITLE
Fix tearing artifacts when scrolling through games.

### PR DESCRIPTION
**Pull request by RonnChyran**
#### What's new?
The text bubbles have been merged with the background and are directly DMA'd to hardware background VRAM as needed instead of being drawn with EasyGL2D. Due to layering limitations, the little bottom arrow part of the text bubbles are still drawn with EasyGL2D on top of the start border.

A queue system using function pointers has also been implemented in order to defer any loading of textures or palettes until the end of the Vblank handler. Palettes are also refreshed automatically every 10 Vblanks at the end of the Vblank handler. Game icons use their own queue system, as lambda captures eventually overflow the available stack space, whereas captureless lambdas are simply optimized as function pointers.

The palette for the dialog box is also now refreshed whenever it is shown.
The source files for the composed background and bubble texture are in the resources folder.

#### What is fixed?
Since we don't have to wait for EasyGL2D to draw most of the title box any more, black artifacting no longer occurs in the top half of the screen. This also frees up valuable texture VRAM, the 'bubble' textures were reduced to 16 by 8 pixels, as most of the bubble is part of the background being directly DMA copied to background VRAM.

By deferring loading of resources into texture RAM until the end of the VBlank handler, the screen is drawn completely without having to wait for resources to be copied to VRAM. This essentially eliminates any remaining black artifacting.

Doing a full palette refresh of text and icons every 10 VBlanks ensures that if palette corruption were to happen, would only appear for a split second before disappearing, instead of having to scroll through games to refresh the font palettes. 

There was also a rare bug where the dialog box would read from a null palette and show up as black and blue. The huge reduction of 3D texture and palette usage (the bubble textures that GL2D was responsible for drawing went from 256x192 to 16x8) as well as a palette refresh every time the dialog is shown should further reduce palette bugs.

This also fixes the font texture corruption bug where the font texture would occasionally corrupt and not restore itself, by reloading the texture into VRAM at the end of the VBlank handler whenever the selected icon is changed.

#### Where have you tested it?
- Nintendo DSi on latest bootstrap, Unlaunch 1.3.
- New Nintendo 3DS on latest bootstrap, Luma 9.1.

*** 
#### Pull Request status
- [x]  This PR has been tested using latest devkitPro, devkitARM, and EasyGL2D.  

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by RonnChyran** [comment]
I've spent a good half hour scrolling through three pages of games and not a single corrupted texture or crash so far, hopefully this PR should quash the last bugs.

**Comment by RonnChyran** [comment]
Never mind, seems like it when it scrolls too fast it guru meditations.

**Comment by RonnChyran** [comment]
It seems like the local arrays used when comparing palettes overflowed the stack, causing the guru meditation errors.

**Comment by RonnChyran** [comment]
2ae025b should fix the Guru Meditation errors.

**Comment by RonnChyran** [comment]
Using a function pointer should stop lambdas from being stack allocated and causing stack dumps.

**Comment by Robz8** [comment]
Is this safe to merge yet?

**Pull request merged**
